### ISSUE TITLE
Deprecate in favor of go-httpbin?

### ISSUE THREAD

**Issue by ahmetb** [arschles/gohttpbin#1]
We have a more extensive version of https://github.com/ahmetalpbalkan/go-httpbin

**Comment by arschles** [comment]
@ahmetalpbalkan sure. I added a `Deprecated` note to the title. Note also that there is a [related repository](https://github.com/arschles/kubehttpbin) that is currently deployed at http://kubehttpbin.org

**Comment by ahmetb** [comment]
@arschles hah, that's pretty cool! Actually, why not contribute a Dockerfile and k8s yml files to the go-httpbin repo we got? I'm happy to accommodate Kubernetes in the repo.

**Comment by arschles** [comment]
@ahmetb Sorry for the delay here. I'm going to keep the kubehttpbin repository as the `main` function (which simply runs the server) and add the Dockerfile and Kubernetes elements. I'll `/cc` you in the PRs as I go, so you can keep up with what's going on if you like.

I'll start contributing core server changes upstream to your repository though. Here's my first: https://github.com/ahmetb/go-httpbin/pull/11

Thanks for the heads up - go-httpbin is _far_ more functional than what's in here!
